# Generated by Django 4.2.1 on 2024-12-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0015_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
