# Generated by Django 4.2.1 on 2024-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0016_remove_product_category_delete_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionuser',
            name='agree',
        ),
        migrations.AlterField(
            model_name='auctionuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
