# Generated by Django 4.2.1 on 2024-12-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bid_app', '0018_alter_auctionuser_adhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionuser',
            name='adhar_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='auctionuser',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='auctionuser',
            name='email_verification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionuser',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='auctionuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
