# Generated by Django 4.2.1 on 2024-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0019_alter_auctionuser_adhar_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='session',
            new_name='end_session_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='endsession',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_session_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='interval_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
