# Generated by Django 4.2.1 on 2024-12-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0021_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interval_price',
        ),
    ]
