# Generated by Django 4.2.1 on 2024-12-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0024_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
